
services:
  nestapp:
    container_name: nestapp
    image: al3xand3r11/nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres 
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}